### ISSUE TITLE
Colour Adjustment Skip

### ISSUE THREAD

**Issue by VGrol** [vedard/Arc-Theme-Generator#1]
**Issue**
When running the script, it seems to skip some colours.
Primarily the top bar and the radio buttons.

![](https://puu.sh/zcc12/cb67a6d253.png)
Note the toolbar colour as well as the missing radio buttons.

**Things I have tried.**
The exact same steps, excluding the script itself.
Works fine, aside from colours changing, obviously.

Both of the black and grey variants, which results in the same problem.

Adding the No Assets flag, makes the radio buttons/toolbar work, but 80% of the theme will be in the default Arc-Theme colour. 

**Appications affected**
Radio and checkmark buttons appear to be globally missing, which is the real problem.
I use 'Lxappearance' to manage the theme and that is the client in the screenshot. Only the preview displays the toolbar though.
'Ark' seems to have the uncoloured tool bar as well as a few other applications.

**Notable environment factors:**
Arch Linux
I3
No primary DE.

**Comment by VGrol** [comment]
I figured out I was missing the Inkscape and optipng dependencies.
Turns out that 'arc-theme' wasn't sufficient and needed ~/ to prefix it.
Only after that would it start displaying the errors in rendering. 

So that is some progress.
Im still having a few problems with some elements however. 

This is my current setup.
![](https://puu.sh/zcg65/314e8ea84c.png)

Atleast Arc and Arc-Darker work accordingly now, It is just Arc-Dark that is throwing everything for a loop.

**Comment by vedard** [comment]
There seems to be a problem when rendering dark asset for Gtk2 application

![screenshot from 2018-01-29 12-45-57](https://user-images.githubusercontent.com/8711046/35525493-a4145b92-04f2-11e8-81e3-af2302acb2af.png)
![screenshot from 2018-01-29 12-46-01](https://user-images.githubusercontent.com/8711046/35525499-a6575792-04f2-11e8-89c3-69b671239a96.png)

**Comment by VGrol** [comment]
I only ended up having that much blue, when I utilized the no-asset flag.
The dependencies solved most of the outliers, except the buttons.
Atleast default and Darker seem to work now.

I tried to play with some exclusions on the ./autogen, but that didn't seem to fix anything.
I think it might just be a missing dependency.
The ./autogen seems to build the theme for Gnome 3.22

**Comment by vedard** [comment]
It's better but not perfect, i have to work on scrollbars and some border a bit
![screenshot from 2018-01-29 13-25-46](https://user-images.githubusercontent.com/8711046/35527186-f0443618-04f7-11e8-97bc-a7a29f01e437.png)

**Comment by vedard** [comment]
Can you try again now with my changement? GTK2 app should look like this now.
![screenshot from 2018-01-29 16-57-32](https://user-images.githubusercontent.com/8711046/35536716-a05588d2-0515-11e8-9b75-c2a390d90c33.png)

**Comment by VGrol** [comment]
Apologies for the delay,
I finally got around to testing the updated script and it works lovely!

Thank you very much for the quick replies and support.
